version: "3.7"

services:
  porfolio-web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/best_project
    ports:
      - "3000:3000"
  db:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: portfolios_page
      POSTGRES_PASSWORD: portfolios_page
      POSTGRES_DB: portfolios_page
    ports:
      - '15432:5432'
volumes:
  postgres:
